export const businessConfig = {
  name: "African Restaurant Sofia",
  shortName: "Restaurant Sofia",
  slogan: "Goûtez l'Afrique. Vivez l'excellence.",
  secondarySlogan: "Saveurs authentiques. Culture riche. Accueil chaleureux.",
  description: "Cuisine ouest-africaine halal authentique au 1580 Park Avenue, à New York.",
  email: "africanrestaurantsofia15@gmail.com",
  whatsappDisplay: "+1 (929) 580-4530",
  whatsappNumber: "19295804530",
  instagramUsername: "@africanrestaurantsofia",
  instagramUrl: "https://www.instagram.com/africanrestaurantsofia",
  facebookUsername: "African Restaurant Sofia",
  facebookUrl: "https://www.facebook.com/profile.php?id=61591448137147",
  tiktokUsername: "@africanrestaurantsofia",
  tiktokUrl: "https://www.tiktok.com/@africanrestaurantsofia",
  address: "1580 Park Avenue, New York, NY 10029",
  locationDisplay: "Cuisine en livraison : 1580 Park Avenue, New York, NY 10029",
  googleMapsUrl: "https://www.google.com/maps/search/?api=1&query=1580%20Park%20Avenue%2C%20New%20York%2C%20NY%2010029",
  googleMapsEmbedUrl: "https://www.google.com/maps?q=1580%20Park%20Avenue%2C%20New%20York%2C%20NY%2010029&output=embed",
  halal: true,
  services: ["Sur place", "À emporter", "Livraison", "Service traiteur"],
  serviceAreas: ["Manhattan", "Brooklyn", "Queens", "The Bronx", "Staten Island"],
  paymentOptions: ["Zelle", "Cash App", "Apple Cash", "Espèces à la livraison", "Carte à la livraison"],
};
